import type {DemoManifestEntry} from "./types";

export const demoManifest: DemoManifestEntry[] = [
    {
        key: "MuzzleFlashDemo",
        name: "Muzzle Flash Performance",
        module: "muzzleFlash",
        sourcePath: "examples/src/demos/muzzleFlash.ts",
        description: "Performance-focused muzzle flash burst systems.",
        tags: ["performance", "burst"],
        preview: {icon: "MF", gradient: "linear-gradient(135deg, #5f83ff 0%, #1e2f72 100%)"},
    },
    {
        key: "ExplosionDemo",
        name: "Explosion (Unity Exported)",
        module: "explosion",
        sourcePath: "examples/src/demos/explosion.ts",
        description: "Explosion effect imported from Unity-authored data.",
        tags: ["explosion", "import"],
        preview: {icon: "EX", gradient: "linear-gradient(135deg, #ff8f56 0%, #a23035 100%)"},
    },
    {
        key: "EmitterShapeDemo",
        name: "Different Emitter Shapes",
        module: "emitterShape",
        sourcePath: "examples/src/demos/emitterShape.ts",
        description: "Compare multiple emitter shape types.",
        tags: ["emitter", "shape"],
        preview: {icon: "ES", gradient: "linear-gradient(135deg, #55d6c2 0%, #21687e 100%)"},
    },
    {
        key: "TrailDemo",
        name: "Trail Renderer and Physics",
        module: "trail",
        sourcePath: "examples/src/demos/trail.ts",
        description: "Trail rendering with runtime physics behavior.",
        tags: ["trail", "physics"],
        preview: {icon: "TR", gradient: "linear-gradient(135deg, #be7bff 0%, #50338e 100%)"},
    },
    {
        key: "SequencerDemo",
        name: "Texture Sequencer",
        module: "sequencer",
        sourcePath: "examples/src/demos/sequencer.ts",
        description: "Animated texture sequence playback on particles.",
        tags: ["texture", "animation"],
        preview: {icon: "SQ", gradient: "linear-gradient(135deg, #f6c55e 0%, #8f5d1f 100%)"},
    },
    {
        key: "MeshMaterialDemo",
        name: "Mesh Material with Environment Map",
        module: "meshMaterial",
        sourcePath: "examples/src/demos/meshMaterial.ts",
        description: "Mesh render mode using Babylon material pipeline.",
        tags: ["mesh", "material"],
        preview: {icon: "MM", gradient: "linear-gradient(135deg, #6ee0ff 0%, #26668e 100%)"},
    },
    {
        key: "SubEmitterDemo",
        name: "Sub Emitter",
        module: "subEmitter",
        sourcePath: "examples/src/demos/subEmitter.ts",
        description: "Spawns secondary particle systems from particles.",
        tags: ["sub-emitter", "event"],
        preview: {icon: "SE", gradient: "linear-gradient(135deg, #ff7dc4 0%, #7d2e75 100%)"},
    },
    {
        key: "TurbulenceDemo",
        name: "Noise Turbulence",
        module: "turbulence",
        sourcePath: "examples/src/demos/turbulence.ts",
        description: "Noise-driven turbulent particle movement.",
        tags: ["noise", "motion"],
        preview: {icon: "NZ", gradient: "linear-gradient(135deg, #70ffa8 0%, #1f7b57 100%)"},
    },
    {
        key: "AlphaTestDemo",
        name: "Alpha Test Mesh Particles",
        module: "alphaTest",
        sourcePath: "examples/src/demos/alphaTest.ts",
        description: "Mesh particles using alpha-tested textures.",
        tags: ["alpha", "mesh"],
        preview: {icon: "AT", gradient: "linear-gradient(135deg, #8cc5ff 0%, #355f99 100%)"},
    },
    {
        key: "CustomPluginDemo",
        name: "Customized Plugin",
        module: "customPlugin",
        sourcePath: "examples/src/demos/customPlugin.ts",
        description: "Custom plugin extension points in action.",
        tags: ["plugin", "extensibility"],
        preview: {icon: "CP", gradient: "linear-gradient(135deg, #b4b8ff 0%, #555bbf 100%)"},
    },
    {
        key: "BillboardDemo",
        name: "Billboard Modes",
        module: "billboard",
        sourcePath: "examples/src/demos/billboard.ts",
        description: "Horizon, vertical and stretched billboard modes.",
        tags: ["billboard", "renderer"],
        preview: {icon: "BB", gradient: "linear-gradient(135deg, #84ffed 0%, #2f7d8a 100%)"},
    },
    {
        key: "SoftParticleDemo",
        name: "Soft Particles and Blend Tiles",
        module: "softParticle",
        sourcePath: "examples/src/demos/softParticle.ts",
        description: "Soft particles with tiled blend techniques.",
        tags: ["soft-particle", "blend"],
        preview: {icon: "SP", gradient: "linear-gradient(135deg, #ffd47e 0%, #92643f 100%)"},
    },
    {
        key: "CustomBlendingDemo",
        name: "Custom Blending Function",
        module: "customBlending",
        sourcePath: "examples/src/demos/customBlending.ts",
        description: "Manual blend function tuning for VFX looks.",
        tags: ["blending", "render"],
        preview: {icon: "CB", gradient: "linear-gradient(135deg, #ff9e7d 0%, #8b3f2c 100%)"},
    },
    {
        key: "FollowObjectDemo",
        name: "Following Moving Objects",
        module: "followObject",
        sourcePath: "examples/src/demos/followObject.ts",
        description: "Particles attached to and following moving objects.",
        tags: ["follow", "gameplay"],
        preview: {icon: "FO", gradient: "linear-gradient(135deg, #a0dcff 0%, #325f8c 100%)"},
    },
    {
        key: "PickUpDemo",
        name: "Pick-Up Burst",
        module: "pickUp",
        sourcePath: "examples/src/demos/pickUp.ts",
        description:
            "Loot sparkle: cone ring, beam, sparks, and mesh up-flow using the shared particle atlas.",
        tags: ["burst", "vfx"],
        preview: {icon: "PU", gradient: "linear-gradient(135deg, #ffe566 0%, #c47a12 100%)"},
    },
    {
        key: "LevelUpDemo",
        name: "Level-Up",
        module: "levelUp",
        sourcePath: "examples/src/demos/levelUp.ts",
        description:
            "Gather burst, dual glow layers, and orbiting cone spray inspired by the three.quarks-editor example.",
        tags: ["burst", "orbit"],
        preview: {icon: "LU", gradient: "linear-gradient(135deg, #fff08a 0%, #8a7a18 100%)"},
    },
    {
        key: "ElectricBallDemo",
        name: "Electric Ball",
        module: "electricBall",
        sourcePath: "examples/src/demos/electricBall.ts",
        description: "Looping electric sphere with secondary atlas and sliding motion.",
        tags: ["loop", "electric"],
        preview: {icon: "EB", gradient: "linear-gradient(135deg, #6ecbff 0%, #1a4f8c 100%)"},
    },
    {
        key: "BlackHoleDemo",
        name: "Black Hole",
        module: "blackhole",
        sourcePath: "examples/src/demos/blackhole.ts",
        description: "Dark core, orbiting accretion gradient, and additive ring using atlas tiles.",
        tags: ["loop", "sci-fi"],
        preview: {icon: "BH", gradient: "linear-gradient(135deg, #2a1a3d 0%, #6b3d9a 100%)"},
    },
    {
        key: "DepthOcclusionTest",
        name: "Depth Occlusion Test (GunFireBlue)",
        module: "depthOcclusionTest",
        sourcePath: "examples/src/demos/depthOcclusionTest.ts",
        description: "Diagnostic harness: alpha-cutout character billboard next to a Unity-exported effect to check depth occlusion.",
        tags: ["diagnostic", "depth", "import"],
        preview: {icon: "DO", gradient: "linear-gradient(135deg, #ff6b6b 0%, #742020 100%)"},
    },
    {
        key: "MagicZoneUnityExample",
        name: "MagicZone: Unity exported by unity-quarks-exporter example",
        module: "MagicZoneUnityExample",
        sourcePath: "examples/src/demos/MagicZoneUnityExample.ts",
        description:
            "MagicZone: Unity exported by unity-quarks-exporter example. This demo shows how to import a Unity authored effect into MagicZone.",
        tags: ["import", "rotation"],
        preview: {icon: "MZ", gradient: "linear-gradient(135deg, #7ec8ff 0%, #2a3f8e 100%)"},
    },
];
